[package]
name = "gen-bindings"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"

[dependencies]
libfp = { path = "../libfp" }
postcard-bindgen = { version = "0.7.1", features = ["generating"] }
