[package]
name = "phoenix-16"
version = "0.1.0"
edition = "2021"

[dependencies]
embassy-embedded-hal = { version = "0.2.0", features = ["defmt"] }
embassy-sync = { version = "0.6.0", features = ["defmt"] }
embassy-executor = { version = "0.6.3", features = [
  "task-arena-size-98304",
  "arch-cortex-m",
  "executor-thread",
  "executor-interrupt",
  "defmt",
  "integrated-timers",
] }
embassy-time = { version = "0.3.2", features = [
  "defmt",
  "defmt-timestamp-uptime",
] }
embassy-usb = { version = "0.3.0", features = [
  "defmt",
  "max-interface-count-6",
] }
embassy-usb-logger = { version = "0.2.0" }
embassy-rp = { version = "0.2.0", features = [
  "defmt",
  "unstable-pac",
  "time-driver",
  "critical-section-impl",
  "rp2040",
  "binary-info",
] }
embassy-futures = { version = "0.1.0" }

cortex-m = { version = "0.7", features = ["inline-asm"] }
cortex-m-rt = "0.7"
defmt = "0.3"
defmt-rtt = "0.4"
panic-probe = { version = "0.3", features = ["print-defmt"] }
smart-leds = "0.4"

critical-section = "1.1"

embedded-hal-async = "1.0"
log = "0.4"

embedded-hal = "1.0"
max11300 = "0.4"
static_cell = "2.1"
portable-atomic = { version = "1.7", features = ["critical-section"] }
pio = "0.2"
pio-proc = "0.2"
drv2605 = "0.1"
sequential-storage = "3.0"
at24cx = "0.1"
wmidi = { version = "4.0", default-features = false }
heapless = "0.8"


[patch.crates-io]
embassy-embedded-hal = { git = "https://github.com/embassy-rs/embassy", rev = "4b1be4787acfb23b3c95c895485843542b44cb97" }
embassy-executor = { git = "https://github.com/embassy-rs/embassy", rev = "4b1be4787acfb23b3c95c895485843542b44cb97" }
embassy-rp = { git = "https://github.com/embassy-rs/embassy", rev = "4b1be4787acfb23b3c95c895485843542b44cb97" }
embassy-sync = { git = "https://github.com/embassy-rs/embassy", rev = "4b1be4787acfb23b3c95c895485843542b44cb97" }
embassy-time = { git = "https://github.com/embassy-rs/embassy", rev = "4b1be4787acfb23b3c95c895485843542b44cb97" }
embassy-usb = { git = "https://github.com/embassy-rs/embassy", rev = "4b1be4787acfb23b3c95c895485843542b44cb97" }
embassy-usb-driver = { git = "https://github.com/embassy-rs/embassy", rev = "4b1be4787acfb23b3c95c895485843542b44cb97" }
embassy-usb-logger = { git = "https://github.com/embassy-rs/embassy", rev = "4b1be4787acfb23b3c95c895485843542b44cb97" }

# release
[profile.release]
lto = true
opt-level = "s"
incremental = false
codegen-units = 1
debug = true

# cargo build/run
[profile.dev]
codegen-units = 1
debug = 2
debug-assertions = true
incremental = false
opt-level = 3
overflow-checks = true

# do not optimize proc-macro crates = faster builds from scratch
[profile.dev.build-override]
codegen-units = 8
debug = false
debug-assertions = false
opt-level = 0
overflow-checks = false
