[package]
name = "phoenix-16"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m = { version = "0.7.6", features = ["inline-asm"] }
cortex-m-rt = "0.7.0"
defmt = "0.3"
defmt-rtt = "0.4"
panic-probe = { version = "0.3", features = ["print-defmt"] }
embassy-executor = { version = "0.5.0", features = ["task-arena-size-32768", "arch-cortex-m", "executor-thread", "executor-interrupt", "defmt", "integrated-timers"] }
embassy-sync = "0.5"
embassy-time = { version = "0.3.0", features = ["defmt", "defmt-timestamp-uptime"] }
embassy-rp = { version = "0.1.0", features = ["defmt", "unstable-pac", "time-driver", "critical-section-impl"] }
embedded-hal = "1.0"
port-expander = "0.5"
# is31fl3218 = { version = "0.2" }
is31fl3218 = { version = "0.3", path = "../is31fl3218"}
max11300 = { path = "../max11300" }
static_cell = "2.0.0"
portable-atomic = { version = "1.6", features = ["critical-section"] }
pio = "0.2.1"
pio-proc = "0.2.2"
embedded-midi = "0.1.2"
