[package]
name = "phoenix-16"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = { version = "0.7", features = ["inline-asm"] }
cortex-m-rt = "0.7"
defmt = "0.3"
defmt-rtt = "0.4"
panic-probe = { version = "0.3", features = ["print-defmt"] }
embassy-executor = { version = "0.6", features = ["task-arena-size-32768", "arch-cortex-m", "executor-thread", "executor-interrupt", "defmt", "integrated-timers"] }
embassy-sync = "0.6"
embassy-time = { version = "0.3", features = ["defmt", "defmt-timestamp-uptime"] }
embassy-rp = { version = "0.2", features = ["defmt", "unstable-pac", "time-driver", "critical-section-impl"] }
embedded-hal = "1.0"
# is31fl3218 = { version = "0.2" }
is31fl3218 = { version = "0.3", path = "../is31fl3218" }
max11300 = { version = "0.3", path = "../max11300" }
static_cell = "2.1"
portable-atomic = { version = "1.7", features = ["critical-section"] }
pio = "0.2"
pio-proc = "0.2"
drv2605 = "0.1"
embassy-usb = "0.3"
embassy-futures = "0.1"
embassy-embedded-hal = "0.2"
sequential-storage = "3.0"
at24cx = { version = "0.1", path = "../at24cx" }
wmidi = { version = "4.0", default-features = false }

# release
[profile.release]
lto = true
opt-level = "s"
incremental = false
codegen-units = 1
debug = true

# cargo build/run
[profile.dev]
codegen-units = 1
debug = 2
debug-assertions = true
incremental = false
opt-level = 3
overflow-checks = true

# do not optimize proc-macro crates = faster builds from scratch
[profile.dev.build-override]
codegen-units = 8
debug = false
debug-assertions = false
opt-level = 0
overflow-checks = false
