//! This build script copies the `memory.x` file from the crate root into
//! a directory where the linker can always find it at build time.
//! For many projects this is optional, as the linker always searches the
//! project root directory -- wherever `Cargo.toml` is. However, if you
//! are using a workspace or have a more complicated build setup, this
//! build script becomes required. Additionally, by requesting that
//! Cargo re-run the build script whenever `memory.x` is changed,
//! updating `memory.x` ensures a rebuild of the application with the
//! new memory settings.

use std::env;
use std::fs::File;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    // Put `memory.x` in our output directory and ensure it's
    // on the linker search path.
    let out = &PathBuf::from(env::var_os("OUT_DIR").unwrap());
    File::create(out.join("memory.x"))
        .unwrap()
        .write_all(include_bytes!("memory.x"))
        .unwrap();
    println!("cargo:rustc-link-search={}", out.display());

    emit_flash_layout(out);

    // By default, Cargo will re-run a build script whenever
    // any file in the project changes. By specifying `memory.x`
    // here, we ensure the build script is only re-run when
    // `memory.x` is changed.
    println!("cargo:rerun-if-changed=memory.x");

    // Extract the version from Cargo.toml for USB configurator
    println!("cargo:rerun-if-changed=Cargo.toml");
    let major = env::var("CARGO_PKG_VERSION_MAJOR").unwrap();
    let minor = env::var("CARGO_PKG_VERSION_MINOR").unwrap();
    let patch = env::var("CARGO_PKG_VERSION_PATCH").unwrap();
    let fpapp_firmware_abi = fpapp_firmware_abi();

    let version_val = (major.parse::<u16>().unwrap() << 8)
        | (minor.parse::<u16>().unwrap() << 4)
        | patch.parse::<u16>().unwrap();

    File::create(out.join("version.rs"))
        .unwrap()
        .write_all(
            format!(
                "// Generated by build.rs from Cargo.toml version and Git revision\npub const USB_RELEASE_VERSION: u16 = 0x{version_val:X};\npub const FIRMWARE_VERSION: (u8, u8, u8) = ({major}, {minor}, {patch});\npub const FPAPP_FIRMWARE_ABI: [u8; 32] = {fpapp_firmware_abi:?};"
            )
            .as_bytes(),
    ).unwrap();

    println!("cargo:rustc-link-arg-bins=--nmagic");
    println!("cargo:rustc-link-arg-bins=-Tlink.x");
    println!("cargo:rustc-link-arg-bins=-Tdefmt.x");
}

/// Emit the linker's FLASH length so `fpapps.rs` can assert against the real
/// value instead of a third hand-maintained copy of it. Without this, raising
/// `memory.x`'s LENGTH lets the firmware grow into the region reserved for
/// installable apps while the guard still passes.
fn emit_flash_layout(out: &Path) {
    println!("cargo:rerun-if-changed=memory.x");
    let text = include_str!("memory.x");
    let length = parse_flash_length(text)
        .expect("memory.x must declare a FLASH region with a LENGTH the build can parse");
    File::create(out.join("flash_layout.rs"))
        .unwrap()
        .write_all(format!("pub const LINKER_FLASH_LEN: usize = {length};\n").as_bytes())
        .unwrap();
}

/// Pull the byte count out of `FLASH : ORIGIN = .., LENGTH = 1536K`.
fn parse_flash_length(text: &str) -> Option<usize> {
    let line = text
        .lines()
        .map(str::trim)
        .find(|line| line.starts_with("FLASH") && line.contains("LENGTH"))?;
    let raw = line
        .rsplit_once("LENGTH")?
        .1
        .trim_start_matches(['=', ' '])
        .trim();
    let raw = raw.split(',').next()?.trim();
    let (digits, scale) = match raw.chars().last()? {
        'K' | 'k' => (&raw[..raw.len() - 1], 1024),
        'M' | 'm' => (&raw[..raw.len() - 1], 1024 * 1024),
        _ => (raw, 1),
    };
    digits.trim().parse::<usize>().ok().map(|n| n * scale)
}

fn fpapp_firmware_abi() -> [u8; 32] {
    println!("cargo:rerun-if-env-changed=FPAPP_FIRMWARE_ABI");
    if let Ok(value) = env::var("FPAPP_FIRMWARE_ABI") {
        return libfp::fpapp::firmware_abi_from_hex(&value)
            .expect("FPAPP_FIRMWARE_ABI must contain exactly 64 hexadecimal digits");
    }

    let revision = firmware_revision();
    libfp::fpapp::firmware_abi_from_revision(&revision)
        .expect("firmware Git revision must contain 40 hexadecimal digits")
}

fn firmware_revision() -> String {
    println!("cargo:rerun-if-env-changed=FADERPUNK_GIT_REVISION");
    if let Ok(revision) = env::var("FADERPUNK_GIT_REVISION") {
        return revision;
    }
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();

    // A linked worktree has a `.git` file rather than `../.git/HEAD`. Ask Git
    // for both the worktree HEAD and its shared branch ref so a new commit
    // always rebuilds the exact-firmware ABI in either checkout shape.
    for path in [
        git_output(&manifest_dir, &["rev-parse", "--git-path", "HEAD"]),
        git_output(&manifest_dir, &["symbolic-ref", "-q", "HEAD"]).and_then(|reference| {
            git_output(
                &manifest_dir,
                &["rev-parse", "--git-path", reference.trim()],
            )
        }),
    ]
    .into_iter()
    .flatten()
    {
        println!("cargo:rerun-if-changed={}", path.trim());
    }

    git_output(&manifest_dir, &["rev-parse", "HEAD"])
        .expect("could not read firmware Git revision")
        .trim()
        .to_owned()
}

fn git_output(manifest_dir: &str, args: &[&str]) -> Option<String> {
    let output = Command::new("git")
        .args(["-C", manifest_dir])
        .args(args)
        .output()
        .expect("git is required to derive the FPApp firmware ABI");
    output
        .status
        .success()
        .then(|| String::from_utf8(output.stdout).expect("Git output must be UTF-8"))
}
