import type { AppLayout } from "./types";

export const testLayout: AppLayout = [
  {
    id: "zxclvkaek",
    appId: 1,
    channels: 2n,
    color: "Red",
    name: "Test App 1",
    description: "Test App 1 Description",
    icon: "Fader",
    paramCount: 0n,
    params: [],
    start: 0,
    end: 1,
  },
  {
    id: "olawrilrjl",
    appId: 1,
    channels: 1n,
    color: "Blue",
    name: "Test App 2",
    description: "Test App 2 Description",
    icon: "Die",
    paramCount: 0n,
    params: [],
    start: 2,
    end: 2,
  },
  {
    id: "jkshg34",
    slotNumber: 3,
  },
  {
    id: "zhpllla",
    appId: 3,
    channels: 8n,
    color: "Yellow",
    name: "Test App 3",
    description: "Test App 3 Description",
    icon: "Sine",
    paramCount: 0n,
    params: [],
    start: 4,
    end: 11,
  },
];
