[package]
name = "fp-sim-app-example"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
embassy-executor = { version = "0.7.0", features = ["arch-std", "executor-thread"] }
embassy-futures = "0.1.0"
embassy-sync = { version = "0.7.2", features = ["std"] }

fp-core = { path = "../fp-core", features = ["log"] }
fp-sim-core = { path = "../fp-sim-core" }
libfp = { path = "../libfp" }
