register_apps!(
    1 => control,
    2 => lfo,
    3 => ad,
    4 => seq8,
    5 => turing,
    6 => clkturing,
    7 => euclid,
    8 => probatrigger,
    9 => notefader,
    10 => offset_att,
    12 => slew,
    13 => follower,
    14 => quantizer,
    15 => midi2cv,
    16 => cv2midi,
    17 => cv2midinote,
);
