register_apps!(
    1 => default,
    2 => lfo,
    3 => ad,
    4 => seq8,
    5 => automator,
    6 => clkcvrnd,
    7 => probatrigger,
    8 => turing,
    9 => clkturing,
    10 => slew,
    11 => follower,
    12 => notefader,
    13 => midi2cv,
    14 => offset_att,
    252 => calibration,
    253 => calibration_unipolar,
    254 => rgbtest,
);
