[package]
name = "config"
version = "0.1.0"
edition = "2021"

[dependencies]
# NOTE: Older version needed by postcard
heapless = "0.7"
serde = { version = "1", features = ["derive"], default-features = false }
postcard-bindgen = "0.7.1"

libfp = { path = "../libfp" }
