[package]
name = "libfp"
version = "0.1.0"
edition = "2021"

[dependencies]
defmt = "1.0"
embassy-time = "0.4.0"
midly = { version = "0.5.3", default-features = false }
postcard = "1.1.2"
serde = { version = "1.0.219", features = ["derive"], default-features = false }
smart-leds = "0.4.0"
