name: Check and Build Firmware (CI)
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'
  pull_request:
    branches:
      - '**'
env:
  CARGO_TERM_COLOR: always
permissions:
  contents: read
jobs:
  lint:
    name: Formatting and Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt
          targets: thumbv8m.main-none-eabihf
      - run: cargo fmt -- --check
      # TODO: enable later
      # - run: cargo clippy --bin faderpunk --target thumbv8m.main-none-eabihf -- -D warnings
      - run: cargo clippy --bin faderpunk --target thumbv8m.main-none-eabihf
  check-bindings:
    name: Try to generate the postcard bindings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      - run: ./gen-bindings.sh
  build_firmware_check:
    name: Build Firmware (Check)
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install System Dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get clean && sudo apt-get update
          sudo apt-get install -y libudev-dev
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: thumbv8m.main-none-eabihf
      - run: cargo install flip-link
      - run: cargo build --bin faderpunk --release --target thumbv8m.main-none-eabihf
